# Generated by Django 4.1.7 on 2023-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=15)),
                ('phone', models.EmailField(max_length=100)),
            ],
        ),
    ]
